wb/main/routes.py
import json
from flask import Blueprint
from flask import render_template, request, url_for, redirect, flash
from wb.models import Order, User
from wb.forms import InputForm
import json
import cgi
from wb import database, bcrypt
from wb.users.utils import save_picture, send_email, delete_file, save_pdf
from datetime import datetime
from flask_login import login_user, current_user, logout_user, login_required
import flask_mail


main =  Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
@main.route('/pedir', methods=['GET', 'POST'])
def home():

    form = InputForm(meta={'locales': ['es_ES', 'es']})

    if form.validate_on_submit():
        if form.file.data:
            # picture_file = save_picture(form.file.data)
            picture_file = save_pdf(form.file.data)
            picture_file = f"files/{picture_file}"
            order = Order(name=form.name.data, email=form.email.data, tel_num=form.tel_num.data, address=form.address.data, order=form.order.data, mop=form.mop.data, file=picture_file)
        else:
            order = Order(name=form.name.data, email=form.email.data, tel_num=form.tel_num.data, address=form.address.data, order=form.order.data, mop=form.mop.data)
        database.session.add(order)
        database.session.commit()
        if form.email.data:
            try:
                send_email(user=order.email, order=order)
                flash("Pedido completado", category='success')
            except:
                flash("Correo electronico no econtrado", category='danger')
                database.session.delete(order)
                database.session.commit()
        else:
            flash("Pedido completado", category='success')
        return redirect(url_for('main.home'))
    return render_template('home.html', form=form)


@main.route('/pedidos', methods=['GET', 'POST'])
@login_required
def pedidos():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=False, is_i_p=False).order_by(Order.date).paginate(per_page=per_page, page=page)
    return render_template('pedidos.html', orders=orders, per_page=per_page)

@main.route('/en_progreso', methods=['GET', 'POST'])
@login_required
def en_progresos():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('en_progreso.html', orders=orders, per_page=per_page)

@main.route('/en_progresar/<id>', methods=['GET', 'POST'])
@login_required
def en_progresar(id):
    order = Order.query.get_or_404(id)
    order.is_i_p = True
    order.date_i_p = datetime.now()
    database.session.commit()

    page=request.args.get('page', 1, type=int)
    orders = Order.query.filter_by(is_completed=False, is_i_p=False).order_by(Order.date).paginate(per_page=10, page=page)
    return render_template('pedidos.html', orders=orders)

@main.route('/delete/<id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    order = Order.query.get_or_404(id)
    delete_file(order.file)
    database.session.delete(order)
    database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=False).order_by(Order.date).paginate(per_page=per_page, page=page)
    return render_template('pedidos.html', orders=orders, per_page=per_page)

@main.route('/delete_all', methods=['GET', 'POST'])
@login_required
def delete_all():
    orders = Order.query.filter_by(is_completed=False)
    for order in orders:
        delete_file(order.file)
        database.session.delete(order)
    database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=False).order_by(Order.date).paginate(per_page=per_page, page=page)
    return render_template('pedidos.html', orders=orders, per_page=per_page)

@main.route('/complete/<id>', methods=['GET', 'POST'])
@login_required
def complete(id):
    order = Order.query.get_or_404(id)
    order.is_completed = True
    order.date_completed = datetime.now()
    delete_file(order.file)
    order.file = ""
    database.session.commit()

    page=request.args.get('page', 1, type=int)
    orders = Order.query.filter_by(is_completed=False).order_by(Order.date).paginate(per_page=10, page=page)
    return render_template('pedidos.html', orders=orders)

@main.route('/complete_all', methods=['GET', 'POST'])
@login_required
def complete_all():
    orders = Order.query.filter_by(is_completed=False)
    for order in orders:
        order.is_completed = True
        order.date_completed = datetime.now()
        delete_file(order.file)
        order.file = ""
    database.session.commit()

    page=request.args.get('page', 1, type=int)
    orders = Order.query.filter_by(is_completed=False).order_by(Order.date).paginate(per_page=10, page=page)
    return render_template('pedidos.html', orders=orders)

@main.route('/epcomplete/<id>', methods=['GET', 'POST'])
@login_required
def epcomplete(id):
    order = Order.query.get_or_404(id)
    order.is_completed = True
    order.date_completed = datetime.now()
    delete_file(order.file)
    order.file = ""
    database.session.commit()

    page=request.args.get('page', 1, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date).paginate(per_page=10, page=page)
    return render_template('en_progreso.html', orders=orders)

@main.route('/epcomplete_all', methods=['GET', 'POST'])
@login_required
def epcomplete_all():
    orders = Order.query.filter_by(is_completed=False, is_i_p=True)
    for order in orders:
        order.is_completed = True
        order.is_i_p = False
        order.date_completed = datetime.now()
        delete_file(order.file)
        order.file = ""
    database.session.commit()

    page=request.args.get('page', 1, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date).paginate(per_page=10, page=page)
    return render_template('en_progreso.html', orders=orders)

@main.route('/completados', methods=['GET', 'POST'])
@login_required
def completados():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('completados.html', orders=orders, per_page=per_page)

@main.route('/delete/<id>/c', methods=['GET', 'POST'])
@login_required
def cdelete(id):
    order = Order.query.get_or_404(id)
    database.session.delete(order)
    database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('completados.html', orders=orders, per_page=per_page)

@main.route('/cdelete/c/all', methods=['GET', 'POST'])
@login_required
def cdelete_all():
    orders = Order.query.filter_by(is_completed=True)
    for order in orders:
        database.session.delete(order)
        database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('completados.html', orders=orders, per_page=per_page)

@main.route('/delete/<id>/ep', methods=['GET', 'POST'])
@login_required
def epdelete(id):
    order = Order.query.get_or_404(id)
    database.session.delete(order)
    database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('en_progreso.html', orders=orders, per_page=per_page)

@main.route('/epdelete/ep/all', methods=['GET', 'POST'])
@login_required
def epdelete_all():
    orders = Order.query.filter_by(is_i_p=True)
    for order in orders:
        database.session.delete(order)
        database.session.commit()
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('en_progreso.html', orders=orders, per_page=per_page)

@main.route('/completados/imprimir', methods=['GET', 'POST'])
@login_required
def completados_print():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_completed=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('completados_print.html', orders=orders, per_page=per_page)

@main.route('/en_progreso/imprimir', methods=['GET', 'POST'])
@login_required
def ep_print():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    orders = Order.query.filter_by(is_i_p=True).order_by(Order.date.desc()).paginate(per_page=per_page, page=page)
    return render_template('ep_print.html', orders=orders, per_page=per_page)

@main.route('/pedidos/print', methods=['GET', 'POST'])
@login_required
def pedidos_print():
    page = request.args.get('page', 1, type=int)

wb/templates/completados.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-black mb-4 ms-4 me-4 ">Pedidos completados:</h1>
    {% for order in orders.items %}
        <div class="card ms-4 me-4 mb-1">
            <div class="card-header">
                <small class="text-black">Fecha del pedido: {{ order.date.strftime('%d %b %Y %H:%M') }},</small><br>
                <small class="text-black">Pedido completado: {{ order.date_completed.strftime('%d %b %Y %H:%M') }}</small>
            </div>
            <div class="card-body">
                <small class="text-black">Nombre: {{ order.name }}</small>
                <small class="text-black d-flex float-end">Numero de telefono: {{ order.tel_num }}</small>
                <br>
                <small class="text-black">Numero de email: {{ order.email }}</small>
                <small class="text-black d-flex float-end">Demicilio: {{ order.address }}</small>
                <br>
                <small class="text-black">Método de pago: {{ order.mop }}</small>
                <p class="article-content text-black"><b>Pedido:</b></p>
                                <a class="btn btn-danger d-flex float-end" href=" {{ url_for('main.cdelete', id=order.id) }}">Borrar</a>
                <p class="article-content text-black">{{ order.order }}</p>
            </div>
        </div>
    {% endfor %}

<div class="mt-4 ms-4">
    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if orders.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.completados', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
        {% endif %}
    {% endfor%}
    {% if per_page != 99999 %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', per_page=99999)}}">Ver todos</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', per_page=10)}}">Ver 10</a>
    {% endif %}
</div>
<div>
    <a href={{url_for('main.completados_print')}} target=”_blank” class="btn btn-primary ms-4 mt-4 mb-4">Imprimir</a>
    <a class="btn btn-danger ms-1 mt-4 mb-4" href=" {{ url_for('main.cdelete_all') }}">Borrar todos</a>
</div>
{% endblock content %}

wb/templates/completados_print.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')  }}">-->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Farmacia Rodriguez</title>
</head>
<body>
    <h1 class="text-black mb-4 ms-4 me-4 ">Pedidos completados:</h1>
    {% for order in orders.items %}
        <div class="card ms-4 me-4 mb-1">
            <div class="card-header">
                <small class="text-black">Fecha del pedido: {{ order.date.strftime('%d %b %Y %H:%M') }},</small>
                <small class="text-black">Pedido completado: {{ order.date_completed.strftime('%d %b %Y %H:%M') }}</small>
            </div>
            <div class="card-body">
                <small class="text-black">Nombre: {{ order.name }}</small>
                <small class="text-black d-flex float-end">Numero de telefono: {{ order.tel_num }}</small>
                <br>
                <small class="text-black">Numero de email: {{ order.email }}</small>
                <small class="text-black d-flex float-end">Demicilio: {{ order.address }}</small>
                <br>
                <small class="text-black">Método de pago: {{ order.mop }}</small>
                <p class="article-content text-black"><b>Pedido:</b></p>
                                <a class="btn btn-danger d-flex float-end" href=" {{ url_for('main.cdelete', id=order.id) }}">Borrar</a>
                <p class="article-content text-black">{{ order.order }}</p>
            </div>
        </div>
    {% endfor %}

<div class="mt-4 ms-4">
    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if orders.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.completados', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
        {% endif %}
    {% endfor%}
    {% if per_page != 99999 %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', per_page=99999)}}">Ver todos</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.completados', per_page=10)}}">Ver 10</a>
    {% endif %}
</div>
<div>
    <button class="btn btn-primary ms-4 mt-4 mb-4" onClick="window.print()">Imprimir</button>
    <a class="btn btn-danger ms-1 mt-4 mb-4" href=" {{ url_for('main.cdelete_all') }}">Borrar todos</a>
</div>
</body>
</html>

wb/templates/en_progreso.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-black mb-4 ms-4 me-4 ">Pedidos que estan en progreso: </h1>
    {% for order in orders.items %}
        <div class="card ms-4 me-4 mb-1">
            <div class="card-header">
                <small class="text-black">Fecha del pedido: {{ order.date.strftime('%d %b %Y %H:%M') }},</small><br>
                <small class="text-black">Fecha marcada como en progreso: {{ order.date_i_p.strftime('%d %b %Y %H:%M') }}</small>
            </div>
            <div class="card-body">
                <small class="text-black">Nombre: {{ order.name }}</small>
                <small class="text-black d-flex float-end">Numero de telefono: {{ order.tel_num }}</small>
                <br>
                <small class="text-black">Numero de email: {{ order.email }}</small>
                <small class="text-black d-flex float-end">Demicilio: {{ order.address }}</small>
                <br>
                <small class="text-black">Método de pago: {{ order.mop }}</small>
                <p class="article-content text-black"><b>Pedido:</b></p>

                <p class="article-content text-black">{{ order.order }}</p>
                {% if order.file %}
                    <a target="_blank" href={{url_for('static',filename=order.file)}}>Archivo</a>
                {% endif %}
                <br>
                                               <a class="btn btn-danger d-flex float-end" href=" {{ url_for('main.epdelete', id=order.id) }}">Borrar</a>
                                  <a class="btn btn-success mt-2" href=" {{ url_for('main.epcomplete', id=order.id) }}">Completar</a>
            </div>
        </div>
    {% endfor %}

<div class="mt-4 ms-4">
    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if orders.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.en_progresos', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.en_progresos', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
        {% endif %}
    {% endfor%}
    {% if per_page != 99999 %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.en_progresos', per_page=99999)}}">Ver todos</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.en_progresos', per_page=10)}}">Ver 10</a>
    {% endif %}
</div>
<div>
    <a href={{url_for('main.ep_print')}} target=”_blank” class="btn btn-primary ms-4 mt-4 mb-4">Imprimir</a>
        <a class="btn btn-success ms-1 mt-4 mb-4" href=" {{ url_for('main.epcomplete_all') }}">Completar todos</a>
    <a class="btn btn-danger ms-1 mt-4 mb-4" href=" {{ url_for('main.epdelete_all') }}">Borrar todos</a>
</div>
{% endblock content %}

wb/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')  }}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Farmacia Rodriguez</title>
</head>
<body>
<!--Navigation-->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <a href={{url_for('main.home')}}><img class="rounded float-start ms-4" src="{{url_for('static',filename = 'images/logo-removebg-preview.png')}}" height="90"></a>

        <div class="container">
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link text-white" href={{url_for('main.pedidos')}}>Pedidos</a>
                    <a class="nav-item nav-link text-white" href={{url_for('main.en_progresos')}}>En progreso</a>
                    <a class="nav-item nav-link text-white" href={{url_for('main.completados')}}>Completados</a>
                {% endif %}
<!--              <a class="nav-item nav-link" href="/">Home</a>-->
                {% block header %}{% endblock %}
            </div>

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="w-100 col-md-8 mx-auto mb-6">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>
      </div>
    </main>
    {% block content %}{% endblock %}
    {% block songs %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
</html>

wb/templates/pedidos.html
{% extends "layout.html" %}
{% block header %}
{% endblock %}


{% block content %}
    <h1 class="text-black mb-4 ms-4 me-4 ">Pedidos:</h1>
    {% for order in orders.items %}
            <div class="card ms-4 me-4 mb-1">

                <div class="card-header">
                    <small class="text-black">{{ order.date.strftime('%d %b %Y %H:%M') }}</small>
                </div>
                <div class="card-body">
                  <small class="text-black">Nombre: {{ order.name }}</small>
                  <small class="text-black d-flex float-end">Numero de telefono: {{ order.tel_num }}</small>
                  <br>
                  <small class="text-black">Email: {{ order.email }}</small>
                  <small class="text-black d-flex float-end">Domicilio: {{ order.address }}</small>
                  <br>
                  <small class="text-black">Método de pago: {{ order.mop }}</small>
                  <p class="article-content text-black"><b>Pedido:</b></p>
                  <p class="article-content text-black">{{ order.order }}</p>
                  {% if order.file %}
                    <a target="_blank" href={{url_for('static',filename=order.file)}}>Archivo</a>
                  {% endif %}
                  <br>
                  <a class="btn btn-success mt-2" href=" {{ url_for('main.complete', id=order.id) }}">Completar</a>
                    <a class="btn btn-secondary mt-2" href=" {{ url_for('main.en_progresar', id=order.id) }}">Marcar como en progreso</a>
                  <a class="btn btn-danger mt-2" href=" {{ url_for('main.delete', id=order.id) }}">Borrar</a>
                </div>
            </div>

    {% endfor %}

<div class="mt-4 ms-4">
    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if orders.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.pedidos', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
        {% endif %}
    {% endfor%}
    {% if per_page != 99999 %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', per_page=99999)}}">Ver todos</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', per_page=10)}}">Ver 10</a>
    {% endif %}
</div>
<div>
    <a href={{url_for('main.pedidos_print')}} target=”_blank” class="btn btn-primary ms-4 mt-4 mb-4">Imprimir</a>
    <a class="btn btn-success ms-1 mt-4 mb-4" href=" {{ url_for('main.complete_all') }}">Completar todos</a>
        <a class="btn btn-secondary ms-1 mt-4 mb-4" href=" {{ url_for('main.ep_all') }}">Marcar todos como en progreso</a>
    <a class="btn btn-danger ms-1 mt-4 mb-4" href=" {{ url_for('main.delete_all') }}">Borrar todos</a>
</div>
{% endblock content %}

wb/templates/pedidos_print.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')  }}">-->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Farmacia Rodriguez</title>
</head>
<body>
    <h1 class="text-black mb-4 ms-4 me-4 ">Pedidos:</h1>
    {% for order in orders.items %}
            <div class="card ms-4 me-4 mb-1">

                <div class="card-header">
                    <small class="text-black">{{ order.date.strftime('%d %b %Y %H:%M') }}</small>
                </div>
                <div class="card-body">
                  <small class="text-black">Nombre: {{ order.name }}</small>
                  <small class="text-black d-flex float-end">Numero de telefono: {{ order.tel_num }}</small>
                  <br>
                  <small class="text-black">Email: {{ order.email }}</small>
                  <small class="text-black d-flex float-end">Domicilio: {{ order.address }}</small>
                  <br>
                  <small class="text-black">Método de pago: {{ order.mop }}</small>
                  <p class="article-content text-black"><b>Pedido:</b></p>
                  <p class="article-content text-black">{{ order.order }}</p>
                  {% if order.file%}
                    <a target="_blank" class="" href={{url_for('static',filename=order.file)}}>Archivo</a>
                  {% endif %}
                  <br>
                  <a class="btn btn-success mt-2" href=" {{ url_for('main.complete', id=order.id) }}">Completar</a>
                  <a class="btn btn-danger mt-2" href=" {{ url_for('main.delete', id=order.id) }}">Borrar</a>
                </div>
            </div>

    {% endfor %}

<div class="mt-4 ms-4">
    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if orders.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.pedidos', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
        {% endif %}
    {% endfor%}
    {% if per_page != 99999 %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', per_page=99999)}}">Ver todos</a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pedidos', per_page=10)}}">Ver 10</a>
    {% endif %}
</div>
<div>
    <button class="btn btn-primary ms-4 mt-4 mb-4" onClick="window.print()">Imprimir</button>
    <a class="btn btn-success ms-1 mt-4 mb-4" href=" {{ url_for('main.complete_all') }}">Completar todos</a>
    <a class="btn btn-danger ms-1 mt-4 mb-4" href=" {{ url_for('main.delete_all') }}">Borrar todos</a>
</div>
</body>
</html>